version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 9000:9000
    networks:
      hadoop:
        ipv4_address: 172.25.1.1

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    networks:
      hadoop:
        ipv4_address: 172.25.1.2

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088
    networks:
      hadoop:
        ipv4_address: 172.25.1.3

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042
    networks:
      hadoop:
        ipv4_address: 172.25.1.4

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
    networks:
      hadoop:
        ipv4_address: 172.25.1.5
  
  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    networks:
      hadoop:
        ipv4_address: 172.25.2.1

  hbase-master:
    image: bde2020/hbase-master:1.2.0
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    volumes:
      - './regionservers:/opt/hbase-1.2.0/conf/regionservers'
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16010:16010
    networks:
      hadoop:
        ipv4_address: 172.25.3.1

  hbase-region:
    image: bde2020/hbase-regionserver:1.2.0
    container_name: hbase-region
    hostname: hbase-region
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030
    networks:
      hadoop:
        ipv4_address: 172.25.3.2

  hive-server:
    image: bde2020/hive:1.1.0-postgresql-metastore
    container_name: hive-server
    hostname: hive-server
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    volumes:
      - "./hadoop/:/opt/hadoop-2.7.4/"
    networks:
      hadoop:
        ipv4_address: 172.25.4.1

  hive-metastore:
    image: bde2020/hive:1.1.0-postgresql-metastore
    container_name: hive-metastore
    hostname: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      hadoop:
        ipv4_address: 172.25.4.2

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:1.1.0
    container_name: hive-metastore-postgresql
    networks:
      hadoop:
        ipv4_address: 172.25.4.3

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoop:
    name: hadoop
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
